apiVersion: v1
kind: Service
metadata:
  name: fuse-pod-manager-node
spec:
  type: NodePort
  selector:
    app: fuse-pod-manager
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090
