contents:
  repositories:
    - https://dl-cdn.alpinelinux.org/alpine/edge/main
    - '@local /work/packages'
  packages:
    - alpine-baselayout-data
    - fuse-fs@local
    - fuse
    - ca-certificates-bundle
accounts:
  run-as: 0
entrypoint:
  command: /usr/bin/fuse-fs
