apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: test
    image: ubuntu
    imagePullPolicy: IfNotPresent
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    securityContext:
      privileged: true
    volumeMounts:
      - mountPath: /tmp/s3-fs-mnt
        name: fs
  volumes:
    - name: fs
      hostPath:
        path: /var/lib/kubelet/plugins/s3-csi/fuse-fs/test
