apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuse-pod-manager-deployment
spec:
  selector:
    matchLabels:
      app: fuse-pod-manager
  template:
    metadata:
      labels:
        app: fuse-pod-manager
    spec:
      serviceAccountName: fuse-pod-manager
      containers:
      - name: fuse-pod-manager
        image: ghcr.io/hown3d/s3-csi/fuse-pod-manager
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "32Mi"
            cpu: "30m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
          - name: K8S_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - containerPort: 9090
