apiVersion: v1
kind: ServiceAccount
metadata:
  name: fuse-pod-manager

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fuse-pod-manager-role
rules:
  - verbs:
      - list
    resources:
      - pods
    apiGroups:
      - ""
  - verbs:
      - create
      - delete
      - patch
    resources:
      - pods
    apiGroups:
      - ""

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fuse-pod-manager-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fuse-pod-manager-role
subjects:
  - kind: ServiceAccount
    name: fuse-pod-manager