name: CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]


jobs:
  ci:
    name: CI
    runs-on: ['ubuntu-latest']
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
        check-latest: true
        cache: true
    - uses: actions/checkout@v3
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...