name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:
  ci:
    name: CI
    runs-on: ['ubuntu-latest']
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
        check-latest: true
        cache: true
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...
  container-build:
    name: Release fuse-fs image
    runs-on: ubuntu-latest
    needs: ci
    strategy:
      matrix:
        variants: ["fuse-fs"]
    permissions:
      id-token: write
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/container-build
        with:
          variant: ${{ matrix.variant }}
          melange-config: melange.${{ matrix.variant}}.yaml
          apko-config: apko.${{ matrix.variant}}.yaml
