name: release
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
jobs:
  container-build:
    name: Release fuse-fs image
    runs-on: ubuntu-latest
    needs: ci
    strategy:
      matrix:
        variants: ["fuse-fs"]
    permissions:
      id-token: write
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/container-build
        with:
          variant: ${{ matrix.variant }}
          melange-config: melange.${{ matrix.variant}}.yaml
          apko-config: apko.${{ matrix.variant}}.yaml
