name: release
concurrency: release
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
jobs:
  build:
    name: Release fuse-fs image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/release
        with:
          variant: fuse-fs
          melange-config: melange.fuse-fs.yaml
          apko-config: apko.fuse-fs.yaml
